[package]
name = "csv_lz4_tool"
version = "0.1.0"
edition = "2021"

[dependencies]
lz4_flex = "0.11"

[[bin]]
name = "mytool"
path = "src/main.rs"

[lib]
name = "csv_lz4_tool"
path = "src/lib.rs"

[[bin]]
name = "chunk_tool"
path = "src/bin/chunking_tools.rs"
